sudo: true
language: python

python:
    - 3.5
    - 3.6

branches:
    only:
       - master

install:
    - pip install coveralls
    - pip install flake8
    - pip install pytest
    - pip install pytest-cov
    - pip install -r requirements.txt

before_script:
    - flake8 peakaboo

script:
    - py.test --pyargs peekaboo --cov-report term-missing --cov=peekaboo

after_success:
    - coverage report
    - coveralls

notifications:
  email: false
  slack: uwdirect:xLvh7uFKIyAfWXQf8hxU0x3X
