sudo: false
language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

branches:
    only:
        - master

install:
    - pip install coverage
    - pip install coveralls
    - pip install flake8
    - pip install pandas

before_script:
    - "flake8 peakaboo"

script:
    - coverage run -m unittest discover

after_success:
    - coverage report
    - coveralls

notifications:
  email: false
  slack: uwdirect:xLvh7uFKIyAfWXQf8hxU0x3X
