sudo: true
language: python

python:
    - 2.7
    - 3.5
    - 3.6

branches:
    only:
        - master

install:
    - pip install coverage
    - pip install coveralls
    - pip install flake8
    - pip install -r requirements.txt
    - git clone git://github.com/scikit-learn-contrib/py-earth.git
    - cd py-earth
    - sudo python setup.py install

before_script:
    - "flake8 peakaboo"

script:
    - coverage run -m unittest discover

after_success:
    - coverage report
    - coveralls

notifications:
  email: false
  slack: uwdirect:xLvh7uFKIyAfWXQf8hxU0x3X
