sudo: true
language: python

python:
    - 2.7
    - 3.5
    - 3.6

branches:
    only:
       - master

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
    - conda install py-earth

install:
    - conda install --yes cython numpy scipy matplotlib nose dateutil pandas patsy statsmodels scikit-learn sympy
    - python setup.py build_ext --inplace --cythonize
    - pip install coverage
    - pip install coveralls
    - pip install flake8
    - pip install -r requirements.txt

before_script:
    - "flake8 peakaboo"

script:
    - coverage run -m unittest discover

after_success:
    - coverage report
    - coveralls

notifications:
  email: false
  slack: uwdirect:xLvh7uFKIyAfWXQf8hxU0x3X
